language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: NCFlYlbldCKg+4Qvx82Gl3C49TwV104ShOx6OIZb1Mrg8GLLAXyAarbsSvxrDOJjZppFa+kbuyS1Mu9AQMZ5Bj/1gqGKhCpAvrUEMG6KZz4evOJRLB5u5fJpum0CbjvizZdjkozuW1j8WfhEFcRI/QrBGxyxjKzddauMQx34Hz/wanoPDjUNECICGF+P5woZUflKfePlK61pLncQZY3vyuELGBNIL/F5KFlAl6quZz00pKexYK1yNLJ2IJnW1Y7O8oVCFAufm7rZN2/QdiNjyaWElieMimVw+hKiWzBqTZvpPwp/MQhqFtn2bIPVAqBbyC80YjreokLFCnDm5eSoJNCluQWhEkepTH/0OMhEW1jWPmnmnijJelQuNhf8hAjLOfYmsgTemHjH1A2Bx1jbXTDYzkEGNSYWiPkkYjpyZZpNzzOt380eVm440P4NZgOoSgRbRnuZZq/rNxcRHT9F2hHhDm73WlrhFg8zTHNCwRC67JUO6DzYpvRmfsMKTdMoopYNkcJiAhWRJxpZXl6oHNNtcS9pfGriz2bZ00Tu/yJ9Qd4av1UxgjnD7dydjzj3S2x7UndiJQPDIzV28i9ktz7Obz61/3Or19Sggvypd8UUt5x6/P5aub61FGPZSg738xFWR4FxSyCIeR4cJ8HmavPSPLmVdaiFF5QG48pw7nQ=
  app:
    master: berlin-ubahn-trip-planner
